### PR TITLE
Add all KASLcred 0.0.8 code

### PR DESCRIPTION
**Pull request by kentbull**
This is all of the code I wrote for the KASLCred utility

### CODE REVIEW

**Review by dhh1128 — CHANGES_REQUESTED** [review]
this looks quite useful to me. However, I suggest we put it in a subdir called "tools" -- so, "tools/kasl", for example, rather than treating the root of the repo as the root of kasl.

**Comment by kentbull** [comment]
Yes, @dhh1128 I agree, I will put it in the "tools" subdirectory.

**Comment by m00sey** [comment]
`tools/KASLcred` would be ideal, in case we have others

**Comment by kentbull** [comment]
Just moved it to /toos/kaslcred

**Review by m00sey — APPROVED** [review]

**Pull request merged**
